#!/bin/bash

source env.sh

CKPOOL_REPO="https://github.com/plebhash/signet-stratum-server.git"
CKPOOL_BRANCH="solobtc-signet-workshop"

if [ ! -e "$STRATUM_SERVER_BIN" ]; then
  echo "Installing build dependencies..."
  sudo apt-get update -qq
  sudo apt-get install -y build-essential autoconf automake libtool yasm pkg-config

  echo "Cloning stratum-server ($CKPOOL_BRANCH branch)..."
  git clone -b "$CKPOOL_BRANCH" "$CKPOOL_REPO" "$STRATUM_SERVER_DIR"

  echo "Building stratum-server..."
  cd "$STRATUM_SERVER_DIR"
  ./autogen.sh
  ./configure
  make

  if [ ! -e "$STRATUM_SERVER_BIN" ]; then
    echo "Build failed. $STRATUM_SERVER_BIN not found."
    exit 1
  fi

  echo "stratum-server built successfully."
  cd ..
else
  echo "Binary $STRATUM_SERVER_BIN already exists. Skipping build."
fi

# Write our config (overwrite any default generated by the build)
cat << 'EOF' > "$STRATUM_SERVER_CONF"
{
    "btcd" : [
        {
            "url" : "localhost:38332",
            "auth" : "user",
            "pass" : "pass",
            "notify" : true
        }
    ],
    "btcaddress" : "your bitcoin address",
    "btcsig" : "your coinbase tag",
    "blockpoll" : 100,
    "update_interval" : 30,
    "serverurl" : [
        "0.0.0.0:3333"
    ],
    "mindiff" : 1,
    "startdiff" : 1,
    "logdir" : "logs"
}
EOF
echo ""
echo "Config written to $STRATUM_SERVER_CONF"
echo ">>> Edit btcaddress and btcsig before starting! <<<"
